# Environment
image: "rust:latest"
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
cache: &global_cache
  paths:
    - target/
    - cargo/
  policy: pull

stages:
- check
- test

# Check
check:
  stage: check
  script:
    - cargo check
  cache:
    <<: *global_cache
    policy: pull-push

clippy:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy
  cache:
    <<: *global_cache
  allow_failure: true

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
