# Environment
image: "rust:latest"
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
- check

# Check
check:
  stage: check
  script:
  - cargo check
  cache:
    paths:
    - target/
    - cargo/

# Test
clippy:
  stage: check
  script:
  - rustup component add clippy
  - cargo clippy
  cache:
    paths:
    - target/
    - cargo/
  allow_failure: true

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
