# Environment
image: "rust:slim"
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - rustup default stable

stages:
- check
- test

# Check
check:
  stage: check
  script:
  - cargo check
  cache:
    paths:
    - target/
    - cargo/

# Test
clippy:
  stage: test
  script:
  - cargo clippy
  cache:
    paths:
    - target/
    - cargo/
  allow_failure: true

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
