stages:
- check
- test

rust-latest:
  stage: check
  image: rust:latest
  script:
  - cargo check
  cache:
    paths:
    - target/

cargo-clippy:
  stage: test
  image: rust:latest
  script:
  - cargo clippy
  cache:
    paths:
    - target/
  allow_failure: true

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
